name: SkyPvP
main: Fludixx\SkyPvP\Main
version: 1
api: 4.0.0
author: Fludixx
description: SkyPvP Plugin
website: https://github.com/Fludixx
commands:
    stats:
        description: "Zeigt deine/andere Stats an"
        aliases: [userstats, st]
    kits:
        description: "Zeigt das Kit Menu an"
        aliases: [getkit, gk, kit]
permissions:
  skypvp.build:
    description: "Erlaubt dir zu auf der Map zu Bauen"
    default: op
